---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s
spec:
  selector:
    matchLabels:
      app: demo-k8s
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
      - name: demo-k8s
        image: ghcr.io/as-polyakov/demo-k8s:v4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s
spec:
  type: LoadBalancer
  selector:
    app: demo-k8s
  ports:
    - name: http
      port: 8090
      protocol: TCP
      targetPort: http
